apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2_6
  namespace: thymeleaf
spec:
  selector:
    matchLabels:
      app: backend2_6
  replicas: 1
  template:
    metadata:
      labels:
         app: backend2_6
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: backend2_6
           image: localhost:5000/backend2_6:latest
           ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend2_6
  namespace: thymeleaf
spec:
#  type: NodePort
  selector:
    app: backend2_6
  ports:
    - protocol: TCP
      port: 8080
#      nodePort: 30001
      targetPort: 8080